# Generated by Django 5.2 on 2025-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_communication_notification_rapport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.RemoveField(
            model_name='communication',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='communication',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
