# Generated by Django 5.2 on 2025-05-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_communication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='catalogue.reservation'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('notification', 'Notification'), ('message', 'Message direct')], max_length=20),
        ),
    ]
